const VIDEOS = {
    M1: {
        1:  { materia: 'EQGBFsGddGw', ejercicio: 'kI7NbWAWbVw' },
        2:  { materia: 'dgAW4OKPDfE', ejercicio: 'LNe43WD8w9U' },
        3:  { materia: 'ArS_zNHfkYw', ejercicio: 'u7_9iWLs9QU' },
        4:  { materia: 'REN2LSbvYEo', ejercicio: 'qEIDwL9nreU' },
        5:  { materia: 'K62bzLOD8D4', ejercicio: '4FWqplJpj1I' },
        6:  { materia: 'tWKolkrPtM0', ejercicio: 'sonOx2_iB9M' },
        7:  { materia: 'HisqbZp6GJM', ejercicio: 'pmpkQAJX-no' },
        8:  { materia: 'nhyQ78aIHgM', ejercicio: 'D_mN5P-hnn4' },
        9:  { materia: '6WaSwa7T9Mg', ejercicio: '7ncI-8Decyg' },
        10:  { materia: '99iyQqELTkA', ejercicio: 'xIhyrrvl0OE' },
        11:  { materia: 'Ywq_jfKaATs', ejercicio: 'MVozgd4JeIY' },
        12:  { materia: 'KwY9GvViv1Y', ejercicio: '25UChMhjOHo' },
        13:  { materia: 'sCnQe8PFf8g', ejercicio: '0XpVqw5fk3U' },
        14:  { materia: 'aWw_CqUR-ZA', ejercicio: '5ooaU7faLos' },
        15:  { materia: 'qFSJzK0bQIA', ejercicio: 'FCuVRP9MmmE' },
        16:  { materia: 'ayn6TfLxb-s', ejercicio: 'G5a1Gxf3x90' },
        17:  { materia: 'HYhsLQCGjoI', ejercicio: 'V6PaygEer_w' },
        18:  { materia: 'Nn2yo3D3v4c', ejercicio: '41iRRcbhIOg' },
        19:  { materia: 'FbErjKsasz4', ejercicio: 'CA6NY8QVCVE' },
        20:  { materia: 'cirGfV_auTE', ejercicio: 'dUcoKvT6R90' }
    },
    CL:  {
        1:  { materia: null, ejercicio: null },
        2:  { materia: null, ejercicio: null },
        3:  { materia: null, ejercicio: null },
        4:  { materia: null, ejercicio: null },
        5:  { materia: null, ejercicio: null },
        6:  { materia: null, ejercicio: null },
        7:  { materia: null, ejercicio: null },
        8:  { materia: null, ejercicio: null },
        9:  { materia: null, ejercicio: null },
        10:  { materia: null, ejercicio: null },
        11:  { materia: null, ejercicio: null },
        12:  { materia: null, ejercicio: null },
        13:  { materia: null, ejercicio: null },
        14:  { materia: null, ejercicio: null },
        15:  { materia: null, ejercicio: null },
        16:  { materia: null, ejercicio: null },
        17:  { materia: null, ejercicio: null },
        18:  { materia: null, ejercicio: null },
        19:  { materia: null, ejercicio: null },
        20:  { materia: null, ejercicio: null }
    },
    M2:  {
        1:  { materia: null, ejercicio: null },
        2:  { materia: null, ejercicio: null },
        3:  { materia: null, ejercicio: null },
        4:  { materia: null, ejercicio: null },
        5:  { materia: null, ejercicio: null },
        6:  { materia: null, ejercicio: null },
        7:  { materia: null, ejercicio: null },
        8:  { materia: null, ejercicio: null },
        9:  { materia: null, ejercicio: null },
        10:  { materia: null, ejercicio: null },
        11:  { materia: null, ejercicio: null },
        12:  { materia: null, ejercicio: null },
        13:  { materia: null, ejercicio: null },
        14:  { materia: null, ejercicio: null },
        15:  { materia: null, ejercicio: null },
        16:  { materia: null, ejercicio: null },
        17:  { materia: null, ejercicio: null },
        18:  { materia: null, ejercicio: null },
        19:  { materia: null, ejercicio: null },
        20:  { materia: null, ejercicio: null }
    },
    HCS: {
        1:  { materia: null, ejercicio: null },
        2:  { materia: null, ejercicio: null },
        3:  { materia: null, ejercicio: null },
        4:  { materia: null, ejercicio: null },
        5:  { materia: null, ejercicio: null },
        6:  { materia: null, ejercicio: null },
        7:  { materia: null, ejercicio: null },
        8:  { materia: null, ejercicio: null },
        9:  { materia: null, ejercicio: null },
        10:  { materia: null, ejercicio: null },
        11:  { materia: null, ejercicio: null },
        12:  { materia: null, ejercicio: null },
        13:  { materia: null, ejercicio: null },
        14:  { materia: null, ejercicio: null },
        15:  { materia: null, ejercicio: null },
        16:  { materia: null, ejercicio: null },
        17:  { materia: null, ejercicio: null },
        18:  { materia: null, ejercicio: null },
        19:  { materia: null, ejercicio: null },
        20:  { materia: null, ejercicio: null }
    },
    CN:  {
        1:  { materia: null, ejercicio: null },
        2:  { materia: null, ejercicio: null },
        3:  { materia: null, ejercicio: null },
        4:  { materia: null, ejercicio: null },
        5:  { materia: null, ejercicio: null },
        6:  { materia: null, ejercicio: null },
        7:  { materia: null, ejercicio: null },
        8:  { materia: null, ejercicio: null },
        9:  { materia: null, ejercicio: null },
        10:  { materia: null, ejercicio: null },
        11:  { materia: null, ejercicio: null },
        12:  { materia: null, ejercicio: null },
        13:  { materia: null, ejercicio: null },
        14:  { materia: null, ejercicio: null },
        15:  { materia: null, ejercicio: null },
        16:  { materia: null, ejercicio: null },
        17:  { materia: null, ejercicio: null },
        18:  { materia: null, ejercicio: null },
        19:  { materia: null, ejercicio: null },
        20:  { materia: null, ejercicio: null }
    }
};

function getVideoId(curso, numero, tipo) {
    return VIDEOS[curso]?.[numero]?.[tipo] || null;
}