const VIDEOS = {
    M1: {
        1:  { materia: null, ejercicio: null },
        2:  { materia: null, ejercicio: null },
        3:  { materia: null, ejercicio: null },
        4:  { materia: null, ejercicio: null },
        5:  { materia: null, ejercicio: null },
        6:  { materia: null, ejercicio: null },
        7:  { materia: null, ejercicio: null },
        8:  { materia: null, ejercicio: null },
        9:  { materia: null, ejercicio: null },
        10:  { materia: null, ejercicio: null },
        11:  { materia: null, ejercicio: null },
        12:  { materia: null, ejercicio: null },
        13:  { materia: null, ejercicio: null },
        14:  { materia: null, ejercicio: null },
        15:  { materia: null, ejercicio: null },
        16:  { materia: null, ejercicio: null },
        17:  { materia: null, ejercicio: null },
        18:  { materia: null, ejercicio: null },
        19:  { materia: null, ejercicio: null },
        20:  { materia: null, ejercicio: null }
    },
    CL:  {
        1:  { materia: null, ejercicio: null },
        2:  { materia: null, ejercicio: null },
        3:  { materia: null, ejercicio: null },
        4:  { materia: null, ejercicio: null },
        5:  { materia: null, ejercicio: null },
        6:  { materia: null, ejercicio: null },
        7:  { materia: null, ejercicio: null },
        8:  { materia: null, ejercicio: null },
        9:  { materia: null, ejercicio: null },
        10:  { materia: null, ejercicio: null },
        11:  { materia: null, ejercicio: null },
        12:  { materia: null, ejercicio: null },
        13:  { materia: null, ejercicio: null },
        14:  { materia: null, ejercicio: null },
        15:  { materia: null, ejercicio: null },
        16:  { materia: null, ejercicio: null },
        17:  { materia: null, ejercicio: null },
        18:  { materia: null, ejercicio: null },
        19:  { materia: null, ejercicio: null },
        20:  { materia: null, ejercicio: null }
    },
    M2:  {
        1:  { materia: null, ejercicio: null },
        2:  { materia: null, ejercicio: null },
        3:  { materia: null, ejercicio: null },
        4:  { materia: null, ejercicio: null },
        5:  { materia: null, ejercicio: null },
        6:  { materia: null, ejercicio: null },
        7:  { materia: null, ejercicio: null },
        8:  { materia: null, ejercicio: null },
        9:  { materia: null, ejercicio: null },
        10:  { materia: null, ejercicio: null },
        11:  { materia: null, ejercicio: null },
        12:  { materia: null, ejercicio: null },
        13:  { materia: null, ejercicio: null },
        14:  { materia: null, ejercicio: null },
        15:  { materia: null, ejercicio: null },
        16:  { materia: null, ejercicio: null },
        17:  { materia: null, ejercicio: null },
        18:  { materia: null, ejercicio: null },
        19:  { materia: null, ejercicio: null },
        20:  { materia: null, ejercicio: null }
    },
    HCS: {
        1:  { materia: null, ejercicio: null },
        2:  { materia: null, ejercicio: null },
        3:  { materia: null, ejercicio: null },
        4:  { materia: null, ejercicio: null },
        5:  { materia: null, ejercicio: null },
        6:  { materia: null, ejercicio: null },
        7:  { materia: null, ejercicio: null },
        8:  { materia: null, ejercicio: null },
        9:  { materia: null, ejercicio: null },
        10:  { materia: null, ejercicio: null },
        11:  { materia: null, ejercicio: null },
        12:  { materia: null, ejercicio: null },
        13:  { materia: null, ejercicio: null },
        14:  { materia: null, ejercicio: null },
        15:  { materia: null, ejercicio: null },
        16:  { materia: null, ejercicio: null },
        17:  { materia: null, ejercicio: null },
        18:  { materia: null, ejercicio: null },
        19:  { materia: null, ejercicio: null },
        20:  { materia: null, ejercicio: null }
    },
    CN:  {
        1:  { materia: null, ejercicio: null },
        2:  { materia: null, ejercicio: null },
        3:  { materia: null, ejercicio: null },
        4:  { materia: null, ejercicio: null },
        5:  { materia: null, ejercicio: null },
        6:  { materia: null, ejercicio: null },
        7:  { materia: null, ejercicio: null },
        8:  { materia: null, ejercicio: null },
        9:  { materia: null, ejercicio: null },
        10:  { materia: null, ejercicio: null },
        11:  { materia: null, ejercicio: null },
        12:  { materia: null, ejercicio: null },
        13:  { materia: null, ejercicio: null },
        14:  { materia: null, ejercicio: null },
        15:  { materia: null, ejercicio: null },
        16:  { materia: null, ejercicio: null },
        17:  { materia: null, ejercicio: null },
        18:  { materia: null, ejercicio: null },
        19:  { materia: null, ejercicio: null },
        20:  { materia: null, ejercicio: null }
    }
};

function getVideoId(curso, numero, tipo) {
    return VIDEOS[curso]?.[numero]?.[tipo] || null;
}